[package]
name = "todo-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
prettytable-rs = "0.10.0"
rustyline = "13.0.0"
rand = "0.8.5"
dialoguer = "0.11.0"